'use strict';

/**
 * Homie Dashboard Proxy
 * ─────────────────────────────────────────────────────────────────────────
 * Runs inside the HA addon container. Responsibilities:
 *
 *  1. Serves homie.html + a generated config.js (zero credentials)
 *  2. For each configured HA connection, opens a /proxy/<id> WebSocket
 *     endpoint that browsers connect to — no token required from the browser
 *  3. For each browser connection, opens a matching server-side WebSocket
 *     to HA using the stored token, injects the auth message, then pipes
 *     all subsequent messages transparently in both directions
 *  4. Rate-limits connection attempts to blunt brute-force attacks
 *  5. Logs every service call (domain.service + entity) for audit trail
 *
 * Token flow:
 *   options.json (HA encrypted) → HOMIE_CONNECTIONS env var → this file
 *   Token is used only in the server→HA WebSocket. Browser never sees it.
 * ─────────────────────────────────────────────────────────────────────────
 */

const express = require('express');
const http    = require('http');
const path    = require('path');
const { WebSocket, WebSocketServer } = require('ws');

// ── Config ────────────────────────────────────────────────────────────────
const PORT = parseInt(process.env.HOMIE_PORT || '3001', 10);
const LOG  = process.env.HOMIE_LOG || 'info';

// Parse connections from env (set by run.sh from options.json)
let CONNECTIONS = [];
try {
  CONNECTIONS = JSON.parse(process.env.HOMIE_CONNECTIONS || '[]');
} catch (e) {
  log('error', `Failed to parse HOMIE_CONNECTIONS: ${e.message}`);
  process.exit(1);
}

if (!CONNECTIONS.length) {
  log('warn', 'No connections configured. Add at least one in the addon Configuration tab.');
}

// Build a lookup map: id → connection object (with token)
const CONN_MAP = {};
CONNECTIONS.forEach(c => {
  if (!c.id || !c.token || !c.ha_url) {
    log('warn', `Skipping invalid connection entry: ${JSON.stringify({ id: c.id, ha_url: c.ha_url })}`);
    return;
  }
  CONN_MAP[c.id] = c;
  log('info', `Registered connection [${c.id}] → ${c.ha_url}${c.wan_url ? ` / ${c.wan_url}` : ''}`);
});

// ── Rate limiting (per IP, per connection id) ─────────────────────────────
// Simple in-memory sliding window — 10 connection attempts per IP per minute
const rateLimitMap = new Map(); // key: `${ip}:${connId}` → [timestamps]
const RATE_LIMIT   = 10;
const RATE_WINDOW  = 60 * 1000; // 1 minute

function isRateLimited(ip, connId) {
  const key  = `${ip}:${connId}`;
  const now  = Date.now();
  const hits = (rateLimitMap.get(key) || []).filter(t => now - t < RATE_WINDOW);
  hits.push(now);
  rateLimitMap.set(key, hits);
  return hits.length > RATE_LIMIT;
}

// Clean up old rate limit entries every 5 minutes
setInterval(() => {
  const cutoff = Date.now() - RATE_WINDOW;
  for (const [key, hits] of rateLimitMap) {
    const fresh = hits.filter(t => t > cutoff);
    if (fresh.length === 0) rateLimitMap.delete(key);
    else rateLimitMap.set(key, fresh);
  }
}, 5 * 60 * 1000);

// ── Express HTTP server ───────────────────────────────────────────────────
const app    = express();
const server = http.createServer(app);

// Serve static dashboard files from /app/www
app.use(express.static(path.join(__dirname, 'www')));

/**
 * GET /client-config.js
 * Generates a credential-free config.js for the browser.
 * Only exposes: id, label, proxyUrl (ws:// pointing back to this proxy).
 * Token is NEVER included.
 */
app.get('/client-config.js', (req, res) => {
  // Determine the host the browser used to reach us
  const host     = req.headers['x-forwarded-host'] || req.headers.host || `homeassistant.local:${PORT}`;
  const proto    = req.headers['x-forwarded-proto'] === 'https' ? 'wss' : 'ws';
  // HA ingress sets X-Ingress-Path (e.g. /api/hassio_ingress/TOKEN).
  // Include it so WebSocket URLs resolve correctly through the ingress proxy.
  const basePath = (req.headers['x-ingress-path'] || '').replace(/\/$/, '');

  const safeConns = CONNECTIONS.map(c => ({
    id:       c.id,
    label:    c.label || c.id,
    proxyUrl: `${proto}://${host}${basePath}/proxy/${encodeURIComponent(c.id)}`,
  }));

  res.setHeader('Content-Type', 'application/javascript');
  res.setHeader('Cache-Control', 'no-store');  // never cache — contains ws URLs
  res.send(`
/* Auto-generated by Homie Proxy addon — no credentials included */
window.HOMIE_CONNECTIONS = ${JSON.stringify(safeConns, null, 2)};
`.trim());
});

// Health check endpoint (used by HA watchdog)
app.get('/health', (_req, res) => res.json({ status: 'ok', connections: Object.keys(CONN_MAP).length }));

// GET /ha-media/:connId/* — proxy HA media files with auth token (browser never sees token)
app.get('/ha-media/:connId/*', (req, res) => {
  const conn = CONN_MAP[req.params.connId];
  if (!conn) { res.status(404).end(); return; }
  const haPath = req.path.replace(`/ha-media/${req.params.connId}`, '');
  const qs     = req.url.includes('?') ? req.url.slice(req.url.indexOf('?')) : '';
  resolveHaUrl(conn).then(haUrl => {
    const fullUrl = haUrl + haPath + qs;
    const mod = haUrl.startsWith('https') ? require('https') : require('http');
    const haReq = mod.get(fullUrl, {
      headers: { Authorization: `Bearer ${conn.token}` },
      rejectUnauthorized: false,
    }, haRes => {
      res.status(haRes.statusCode);
      const ct = haRes.headers['content-type'];
      if (ct) res.setHeader('Content-Type', ct);
      res.setHeader('Cache-Control', 'max-age=60');
      haRes.pipe(res);
    });
    haReq.on('error', () => res.status(502).end());
  }).catch(() => res.status(502).end());
});

// Catch-all: serve homie.html for any unknown path (SPA behaviour)
app.get('*', (_req, res) => {
  res.sendFile(path.join(__dirname, 'www', 'homie.html'));
});

// ── WebSocket proxy server ────────────────────────────────────────────────
// No path option — ws exact-matches the full URL so /proxy/<id> would never
// match /proxy. Route manually in the handler instead.
const wss = new WebSocketServer({ server });

// Log every WS upgrade attempt so we can tell if the browser is reaching us
server.on('upgrade', (req) => {
  log('info', `WS upgrade request: ${req.url}`);
});

// Route: ws://host/proxy/<connId>
wss.on('connection', (browserWs, req) => {
  // Parse the connection ID from the URL path: /proxy/<id>
  const parts  = req.url.split('/').filter(Boolean); // ['proxy', '<id>']
  if (parts[0] !== 'proxy') { browserWs.close(4404, 'Not found'); return; }
  const connId = decodeURIComponent(parts[1] || '');
  const conn   = CONN_MAP[connId];

  // Derive client IP (respects X-Forwarded-For from HA ingress proxy)
  const ip = (req.headers['x-forwarded-for'] || req.socket.remoteAddress || '').split(',')[0].trim();

  if (!conn) {
    log('warn', `[${ip}] Unknown connection id: "${connId}" — closing`);
    browserWs.close(4004, 'Unknown connection');
    return;
  }

  if (isRateLimited(ip, connId)) {
    log('warn', `[${ip}] Rate limit exceeded for connection [${connId}] — dropping`);
    browserWs.close(4029, 'Too many requests');
    return;
  }

  log('info', `[${ip}] Browser connected → proxy [${connId}]`);

  // ── Resolve HA URL (LAN preferred, WAN fallback) ──────────────────────
  resolveHaUrl(conn).then(haUrl => {
    const wsUrl = haUrl.replace(/^http/, 'ws') + '/api/websocket';
    log('info', `[${connId}] Opening server-side WS → ${wsUrl}`);

    let haWs;
    try {
      haWs = new WebSocket(wsUrl, { rejectUnauthorized: false });
    } catch (e) {
      log('error', `[${connId}] Failed to open WS to HA: ${e.message}`);
      browserWs.close(1011, 'Proxy upstream error');
      return;
    }

    let authDone = false;

    // ── HA → browser (server-side receives, forwards to browser) ─────────
    haWs.on('message', raw => {
      let msg;
      try { msg = JSON.parse(raw); } catch { return; }

      // Intercept auth_required: inject the token ourselves
      // The browser never sends a token — we do it here
      if (msg.type === 'auth_required' && !authDone) {
        log('debug', `[${connId}] HA requested auth — injecting token server-side`);
        haWs.send(JSON.stringify({ type: 'auth', access_token: conn.token }));
        return; // do NOT forward auth_required to browser
      }

      if (msg.type === 'auth_ok') {
        authDone = true;
        log('info', `[${connId}] HA auth OK — proxy is live`);
        // Forward auth_ok so the browser knows the connection is ready
      }

      if (msg.type === 'auth_invalid') {
        log('error', `[${connId}] HA rejected token — check addon configuration`);
      }

      // Forward everything else to the browser
      if (browserWs.readyState === WebSocket.OPEN) {
        browserWs.send(raw);
      }
    });

    haWs.on('close', (code, reason) => {
      log('info', `[${connId}] HA WS closed: ${code} ${reason}`);
      if (browserWs.readyState === WebSocket.OPEN) browserWs.close(code, reason);
    });

    haWs.on('error', e => {
      log('error', `[${connId}] HA WS error: ${e.message}`);
      if (browserWs.readyState === WebSocket.OPEN) browserWs.close(1011, 'Upstream error');
    });

    // ── Browser → HA (browser sends, proxy forwards to HA) ───────────────
    browserWs.on('message', raw => {
      // Audit log: record every service call
      try {
        const msg = JSON.parse(raw);
        if (msg.type === 'call_service') {
          log('info', `[${connId}][AUDIT] service_call: ${msg.domain}.${msg.service} entity=${msg.service_data?.entity_id || '—'}`);
        }
        // Block any attempt by the browser to send an auth message
        // (the token should only come from the server side)
        if (msg.type === 'auth') {
          log('warn', `[${ip}] Browser attempted to send auth token — blocked`);
          return;
        }
      } catch { /* non-JSON, pass through */ }

      if (haWs.readyState === WebSocket.OPEN) {
        haWs.send(raw);
      }
    });

    browserWs.on('close', (code, reason) => {
      log('info', `[${ip}] Browser disconnected from [${connId}]: ${code}`);
      if (haWs.readyState === WebSocket.OPEN) haWs.close();
    });

    browserWs.on('error', e => {
      log('warn', `[${ip}] Browser WS error: ${e.message}`);
      if (haWs.readyState === WebSocket.OPEN) haWs.close();
    });

  }).catch(e => {
    log('error', `[${connId}] URL resolution failed: ${e.message}`);
    browserWs.close(1011, 'Proxy upstream unavailable');
  });
});

// ── HA URL resolver (LAN first, WAN fallback, 1.5 s timeout) ─────────────
function resolveHaUrl(conn) {
  const lan = conn.ha_url  || '';
  const wan = conn.wan_url || '';

  if (!lan) return Promise.resolve(wan);
  if (!wan || wan === lan) return Promise.resolve(lan);

  return new Promise(resolve => {
    const timer = setTimeout(() => resolve(wan), 1500);

    const https = lan.startsWith('https') ? require('https') : require('http');
    const req = https.request(
      `${lan}/api/`,
      { method: 'HEAD', headers: { Authorization: `Bearer ${conn.token}` }, timeout: 1400, rejectUnauthorized: false },
      res => {
        clearTimeout(timer);
        resolve(res.statusCode < 400 ? lan : wan);
        res.resume();
      }
    );
    req.on('error',   () => { clearTimeout(timer); resolve(wan); });
    req.on('timeout', () => { clearTimeout(timer); resolve(wan); req.destroy(); });
    req.end();
  });
}

// ── Logging ───────────────────────────────────────────────────────────────
function log(level, msg) {
  const levels = { debug: 0, info: 1, warn: 2, error: 3 };
  if ((levels[level] ?? 1) < (levels[LOG] ?? 1)) return;
  const prefix = { debug: '🔍', info: '✔', warn: '⚠', error: '✖' }[level] || '·';
  const ts = new Date().toISOString().replace('T', ' ').slice(0, 19);
  console.log(`[${ts}] ${prefix} ${msg}`);
}

// ── Start ─────────────────────────────────────────────────────────────────
server.listen(PORT, '0.0.0.0', () => {
  log('info', `Homie proxy running on port ${PORT}`);
  log('info', `Dashboard: http://homeassistant.local:${PORT}/`);
  log('info', `Proxy endpoints: ${Object.keys(CONN_MAP).map(id => `/proxy/${id}`).join(', ') || 'none'}`);
});

// Graceful shutdown
process.on('SIGTERM', () => { log('info', 'SIGTERM received — shutting down'); server.close(() => process.exit(0)); });
process.on('SIGINT',  () => { log('info', 'SIGINT received  — shutting down'); server.close(() => process.exit(0)); });
